/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import strapiCloud from "@strapi/plugin-cloud/strapi-admin";
import colorPicker from "@strapi/plugin-color-picker/strapi-admin";
import i18N from "@strapi/plugin-i18n/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import commentManager from "strapi-plugin-comment-manager/strapi-admin";
import comments from "strapi-plugin-comments/strapi-admin";
import graphsBuilder from "strapi-plugin-graphs-builder/strapi-admin";
import entityNotes from "strapi-plugin-notes/strapi-admin";
import plausible from "strapi-plugin-plausible/strapi-admin";
import todo from "strapi-plugin-todo/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

renderAdmin(document.getElementById("strapi"), {
  plugins: {
    "strapi-cloud": strapiCloud,
    "color-picker": colorPicker,
    i18n: i18N,
    "users-permissions": usersPermissions,
    "comment-manager": commentManager,
    comments: comments,
    "graphs-builder": graphsBuilder,
    "entity-notes": entityNotes,
    plausible: plausible,
    todo: todo,
  },
});
